#!/bin/bash

if hash virtualenv 2>/dev/null; then
  if [ ! -d virtualenv ]; then
    virtualenv --no-site-packages virtualenv
  fi
  source ./virtualenv/bin/activate
fi

pip install -r requirements.txt

ENV=env.ct
if [ ! -f $ENV ]; then
  echo "API_TYPE=http" >> $ENV
  echo "PROTOCOL=http" >> $ENV
  echo "HOST=192.168.1.28" >> $ENV
  echo "PORT=49160" >> $ENV
  echo "CLI_TYPE=curses" >> $ENV
fi
