#!/bin/bash

if hash virtualenv 2>/dev/null; then
  if [ ! -d virtualenv ]; then
    virtualenv --no-site-packages virtualenv
  fi
  source ./virtualenv/bin/activate
fi
pip install -r requirements.txt

ENV=env.ct
if [ ! -f $ENV ]; then
  echo "WEBROOT=http://localhost:49160" >> $ENV
fi
